# Generated by Django 5.1.2 on 2024-11-05 09:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasksapp", "0002_task_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="user",
            new_name="user_id",
        ),
    ]
